{% set version = "0.11.0" %}

package:
  name: camelot-py
  version: {{ version }}

source:
  url: https://github.com/camelot-dev/camelot/archive/v{{ version }}.tar.gz
  sha256: 7a019a53cd331a4e864142f1330980367314ff97452267c45c5d185e7774debf

build:
  noarch: python
  number: 1
  entry_points:
    - camelot = camelot.cli:cli
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - tk
    - ghostscript
    - chardet >=3.0.4
    - click >=6.7
    - matplotlib-base >=2.2.3
    - numpy >=1.13.3
    - opencv >=3.2.0
    - openpyxl >=2.5.8
    - pandas >=0.23.4
    - pdfminer.six >=20200726
    - pycryptodome
    - pypdf >=3
    - python >={{ python_min }}
    - python-ghostscript
    - tabulate >=0.8.9
    - pdftopng

test:
  imports:
    - camelot
  commands:
    - camelot --help
  requires:
    - python {{ python_min }}

about:
  home: http://camelot-py.readthedocs.io/
  license: MIT
  license_file: LICENSE
  summary: PDF Table Extraction for Humans.

extra:
  recipe-maintainers:
    - vinayak-mehta
    - izahn
