{% set version = "0.10.1" %}

package:
  name: camelot-py
  version: {{ version }}

source:
  url: https://github.com/camelot-dev/camelot/archive/v{{ version }}.tar.gz
  sha256: 4262ad5cfcf45d0c99097e24a58125337bf399ff752df1c80325ec87be1f3906

build:
  noarch: python
  number: 1
  entry_points:
    - camelot = camelot.cli:cli
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3
    - setuptools
    - pip
  run:
    - tk
    - ghostscript
    - python-ghostscript
    - chardet >=3.0.4
    - click >=6.7
    - matplotlib-base >=2.2.3
    - numpy >=1.13.3
    - opencv >=3.2.0
    - openpyxl >=2.5.8
    - pandas >=0.23.4
    - pdfminer.six >=20200726
    - pycryptodome
    - pypdf2 >=1.26.0
    - python >=3
    - tabulate >=0.8.9
    - pdftopng

test:
  files:
   - agstat.pdf
  imports:
    - camelot
  commands:
    - camelot --help
    - python -c "import camelot; camelot.read_pdf('agstat.pdf')"

about:
  home: http://camelot-py.readthedocs.io/
  license: MIT
  license_file: LICENSE
  summary: PDF Table Extraction for Humans.

extra:
  recipe-maintainers:
    - vinayak-mehta
    - izahn
