{% set version = "0.8.1" %}

package:
  name: camelot-py
  version: {{ version }}

source:
  url: https://github.com/camelot-dev/camelot/archive/v{{ version }}.tar.gz
  sha256: 48e52a5f8884f4c868a6ece9cff4a9d3e2257612f625f2be39a70f1fa444b81c

build:
  noarch: python
  number: 0
  entry_points:
    - camelot = camelot.cli:cli
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3
    - setuptools
    - pip
  run:
    - tk
    - ghostscript
    - click >=6.7
    - matplotlib-base >=2.2.3
    - numpy >=1.13.3
    - opencv >=3.2.0
    - openpyxl >=2.5.8
    - pandas >=0.23.4
    - pdfminer.six >=20181108
    - pycryptodome
    - pypdf2 >=1.26.0
    - python >=3

test:
  imports:
    - camelot
  commands:
    - camelot --help

about:
  home: http://camelot-py.readthedocs.io/
  license: MIT
  license_file: LICENSE
  summary: PDF Table Extraction for Humans.

extra:
  recipe-maintainers:
    - vinayak-mehta
