{% set name = "camelot-py" %}
{% set version = "1.0.9" %}
package:
  name: {{ name|lower }}
  version: {{ version }}
source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/camelot_py-{{ version }}.tar.gz
  sha256: d43d88766f7c3462803ff11464e7d3d15a9223e845972de2b61ef7c3f62d3200
build:
  skip: true  # [py<39 or win]
  entry_points:
    - camelot = camelot.__main__:main
  script: {{ PYTHON }} -m pip install . -vv
  number: 1
requirements:
  host:
    - python {{ python }}
    - pip
  run:
    - python {{ python }}
    - click >=8.0.1
    - pillow >=10.4.0
    - chardet >=5.1.0
    - numpy >=1.24.4  # [py<312]
    - numpy >=1.26.1  # [py>=312]
    - openpyxl >=3.1.0
    - pdfminer-six
    - pypdf >=3.17,<4.0  # [py<312]
    - pypdf >=4.0,<6.0  # [py>=312]
    - pandas >=1.5.3  # [py<310]
    - pandas >=2.2.2  # [py>=310]
    - tabulate >=0.9.0
    - typing_extensions >=4.12.2  # [py<311]
    - opencv >=4.7.0.68
    - pypdfium2 >=4
test:
  imports:
    - camelot
  commands:
    - pip check
    - camelot --help
  requires:
    - pip
about:
  home: http://camelot-py.readthedocs.io/
  license: MIT
  license_file: LICENSE
  summary: PDF Table Extraction for Humans.

extra:
  recipe-maintainers:
    - vinayak-mehta
    - bosd
    - izahn
    - AaronOpfer
