{% set version = "1.0.0" %}

package:
  name: camelot-py
  version: {{ version }}

source:
  url: https://github.com/camelot-dev/camelot/archive/v{{ version }}.tar.gz
  sha256: 1a9e0b36d0dea28aab6aae4cf21da8f82ab612abfa585efab3b60ab30b243ed6

build:
  noarch: python
  number: 0
  entry_points:
    - camelot = camelot.cli:cli
  script: {{ PYTHON }} -m pip install . --no-deps -vv

requirements:
  host:
    - python >=3
    - setuptools
    - pip
  run:
    - chardet >=3.0.4
    - click >=6.7
    - numpy >=1.13.3
    - openpyxl >=2.5.8
    - pdfminer.six >=20200726
    - pypdf >=3
    - pandas >=0.23.4
    - tabulate >=0.8.9
    - matplotlib-base >=2.2.3
    - opencv >=3.2.0
    - pypdfium2 >=4
    - python >=3
    - tk

test:
  imports:
    - camelot
  commands:
    - camelot --help

about:
  home: http://camelot-py.readthedocs.io/
  license: MIT
  license_file: LICENSE
  summary: PDF Table Extraction for Humans.

extra:
  recipe-maintainers:
    - vinayak-mehta
    - bosd
    - izahn
