# This file was generated automatically from conda-smithy. To update this configuration,
# update the conda-forge.yml and/or the recipe/meta.yaml.

language: generic

os: osx
osx_image: xcode9.4


env:
  matrix:
    - CONFIG=osx_python2.7
    - CONFIG=osx_python3.6

  global:
    # The BINSTAR_TOKEN secure variable. This is defined canonically in conda-forge.yml.
    - secure: "Yo0NZFl5HfCFxjEPQS1gYUmxkNh2getDy6iOAhCqguFIu/KmXK3WTFhKgWK50B5S/3wyZ3mU9fvTp5GhZlQPEuFP2NQLCEoVUmQVK6FSlOskVNY0zIV1w0s13siZC/bjp4uNqJMb0w6GninaPuxEsRRXN0Hq5nxEeykVeTo+626r/wIpioBzrWOsmfKw4cDmYc3WkL4Gl3klvLUZAc7whYA52HyufVHJ409IG1mV6DJSNhYsalVDW88865D/1kie3J+13OQFMo3vORVruOYPp/Y7kMdgCczLg0oo8XjX2OrSySRTDfblDyPLMrz8biXF7jtG1yzU8npZ7hsR+Q5VwD6Vb2AKWQy5FqHJuf5u1ylVH3MFC3B417jM86Bz19ekjDh+6N6w4ExnQXdAJ9QtebxGuzO+C+xad/Vf3sIMDUPOBGMaDywfsJ/G+Ax9bH5WCQ3BMxmduczs2NDtT3w6x/mH/iamG4BJ1X49xYB9ywSuWo1PChtHwsIc/7qrm7ilL3eQyI+79HxS5ukMydyYQhPpEHjksfDRCaJazSo/uBE7o7so7Jmwh7VGHBxsFuprw26DMX9EmEinX1heSNP4D6t3siQ1LJiirnN6moS+6zJ6ART2zbSJtSHJnXeyZm/iK98oWLCpicDstm+Mt4jCZwClmteooCbe/YNErQFGFGo="


before_install:
    # Fast finish the PR.
    - |
      (curl https://raw.githubusercontent.com/conda-forge/conda-forge-ci-setup-feedstock/branch2.0/recipe/conda_forge_ci_setup/ff_ci_pr_build.py | \
          python - -v --ci "travis" "${TRAVIS_REPO_SLUG}" "${TRAVIS_BUILD_NUMBER}" "${TRAVIS_PULL_REQUEST}") || exit 1

    # Remove homebrew.
    - |
      echo ""
      echo "Removing homebrew from Travis CI to avoid conflicts."
      curl -fsSL https://raw.githubusercontent.com/Homebrew/install/master/uninstall > ~/uninstall_homebrew
      chmod +x ~/uninstall_homebrew
      ~/uninstall_homebrew -fq
      rm ~/uninstall_homebrew


install:
    # Install Miniconda.
    - |
      echo ""
      echo "Installing a fresh version of Miniconda."
      MINICONDA_URL="https://repo.continuum.io/miniconda"
      MINICONDA_FILE="Miniconda3-latest-MacOSX-x86_64.sh"
      curl -L -O "${MINICONDA_URL}/${MINICONDA_FILE}"
      bash $MINICONDA_FILE -b

    # Configure conda.
    - |
      echo ""
      echo "Configuring conda."
      source /Users/travis/miniconda3/bin/activate root

      conda install -n root -c conda-forge --quiet --yes conda-forge-ci-setup=2
      setup_conda_rc ./ ./recipe ./.ci_support/${CONFIG}.yaml

      source run_conda_forge_build_setup

    # compiler cleanup
    - |
      mangle_compiler ./ ./recipe ./.ci_support/${CONFIG}.yaml

script:
  # generate the build number clobber
  - make_build_number ./ ./recipe ./.ci_support/${CONFIG}.yaml
  - conda build ./recipe -m ./.ci_support/${CONFIG}.yaml --clobber-file ./.ci_support/clobber_${CONFIG}.yaml
  - upload_package ./ ./recipe ./.ci_support/${CONFIG}.yaml